"""empty message

Revision ID: 34019587ad4b
Revises: 53719723146b
Create Date: 2021-09-02 03:59:59.720288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34019587ad4b'
down_revision = '53719723146b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diameterPlanet', sa.String(length=30), nullable=False),
    sa.Column('gravityPlanet', sa.String(length=30), nullable=False),
    sa.Column('populationPlanet', sa.String(length=30), nullable=False),
    sa.Column('climatePlanet', sa.String(length=30), nullable=False),
    sa.Column('terrainPlanet', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namePersonaje', sa.String(length=30), nullable=False),
    sa.Column('urlPersonaje', sa.String(length=30), nullable=False),
    sa.Column('imgPersonaje', sa.String(length=30), nullable=False),
    sa.Column('heightPersonaje', sa.String(length=30), nullable=False),
    sa.Column('massPersonaje', sa.String(length=30), nullable=False),
    sa.Column('hairColorPersonaje', sa.String(length=30), nullable=False),
    sa.Column('skinColorPersonaje', sa.String(length=30), nullable=False),
    sa.Column('eyeColorPersonaje', sa.String(length=30), nullable=False),
    sa.Column('homeWorldPersonaje', sa.String(length=30), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personaje')
    op.drop_table('planet')
    # ### end Alembic commands ###
